spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  web:
    resources:
      chain:
        cache: false
  thymeleaf:
    cache: false
logging:
  level:
    org.hibernate.SQL: DEBUG
vite:
  mode: dev