spring:
  web:
    resources:
      cache:
        period: 365d
        cachecontrol:
          max-age: 365d
          cache-public: true
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /images/**
  datasource:
    url: jdbc:postgresql://db:5432/todo
    username: postgres
    password: root
logging:
  structured:
    format:
      console: io.github.dutianze.springbootthymeleafreact.shared.log.CloudWatchLogFormatter
vite:
  mode: build
  build-mode-context-path: /
